import os
import re
import sys
import json
import datetime

# Import the (heavy) PDF/font stack at MODULE LOAD — before stdio_server() takes
# over stdout. Importing fpdf -> fontTools -> Pillow lazily inside the tool
# handler deadlocks the stdio JSON-RPC transport on Windows (the C-extension
# import races the asyncio stdout reader), which surfaced as a 30s tool timeout.
from fpdf import FPDF

# Shared helpers. This server runs as a standalone stdio subprocess (launched by
# file path), so we import the sibling modules directly rather than
# `from app.pdf_filler import ...` — the latter would run app/__init__ and pull
# in the whole agent stack. Both modules keep heavy libs lazy / are stdlib-only,
# so these imports stay light and do not risk the stdio deadlock noted above.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pdf_filler  # noqa: E402
import knowledge_base as kb  # noqa: E402  (shared, self-populating scheme/form catalog)

from mcp.server import Server, NotificationOptions
from mcp.server.stdio import stdio_server
from mcp.server.models import InitializationOptions
from mcp.types import Tool, TextContent

server = Server("sugam-mcp-server")

# --------------------------------------------------------------------------- #
# Paths — write generated PDFs into <project_root>/artifacts/
# --------------------------------------------------------------------------- #
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_ARTIFACTS_DIR = os.path.join(_PROJECT_ROOT, "artifacts")

# Named-form field lists and government-scheme details now live in the shared
# `knowledge_base` module, which backs every lookup with a curated seed catalog
# PLUS a self-populating JSON store the agent's grounded-research tools write to.
# So a scheme/form missing from the seed is no longer a dead-end: once it has
# been researched once, these tools find it here on every subsequent call.

# --------------------------------------------------------------------------- #
# Tool declarations
# --------------------------------------------------------------------------- #
@server.list_tools()
async def handle_list_tools() -> list[Tool]:
    return [
        Tool(
            name="parse_form_fields",
            description="Returns the real list of required fields (with plain-language descriptions) for a known official form.",
            inputSchema={
                "type": "object",
                "properties": {
                    "form_id": {"type": "string", "description": "Form name, e.g. 'KYC', 'PAN', 'AADHAAR'"}
                },
                "required": ["form_id"],
            },
        ),
        Tool(
            name="lookup_govt_scheme",
            description="Looks up real eligibility criteria, benefits and required documents for a government scheme.",
            inputSchema={
                "type": "object",
                "properties": {
                    "scheme_name": {"type": "string", "description": "Scheme name, e.g. 'PM-KISAN', 'Ayushman Bharat'"}
                },
                "required": ["scheme_name"],
            },
        ),
        Tool(
            name="generate_filled_pdf",
            description="Generates a real filled PDF from collected user data and saves it to the artifacts folder. Returns the file path.",
            inputSchema={
                "type": "object",
                "properties": {
                    "form_id": {"type": "string", "description": "The form name, e.g. 'KYC'"},
                    "user_data": {"type": "string", "description": "JSON object (as a string) of field name -> value"},
                },
                "required": ["form_id", "user_data"],
            },
        ),
    ]


# --------------------------------------------------------------------------- #
# Tool implementations
# --------------------------------------------------------------------------- #
def _build_pdf(form_id: str, data: dict) -> str:
    """Render a real, well-formatted PDF and return its absolute path."""
    os.makedirs(_ARTIFACTS_DIR, exist_ok=True)

    pdf = FPDF()
    pdf.add_page()

    # Register a Unicode font when available so native-language values render.
    unicode_ok = pdf_filler.register_unicode_font(pdf)
    font = "uni" if unicode_ok else "helvetica"

    def text(value: str) -> str:
        # If we only have a Latin font, drop characters it cannot encode.
        if unicode_ok:
            return value
        return value.encode("latin-1", "replace").decode("latin-1")

    pdf.set_font(font, "B", 16)
    pdf.cell(0, 12, text(f"{form_id.upper()} - Filled Application"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font(font, "", 10)
    stamp = datetime.datetime.now().strftime("%d %b %Y, %H:%M")
    pdf.set_text_color(110, 110, 110)
    pdf.cell(0, 8, text(f"Generated by Sugam Form Filler on {stamp}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    for key, value in data.items():
        label = str(key).replace("_", " ").title()
        pdf.set_font(font, "B", 11)
        pdf.multi_cell(0, 8, text(f"{label}:"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(font, "", 11)
        pdf.multi_cell(0, 8, text(str(value)), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    safe_id = re.sub(r"[^A-Za-z0-9]+", "_", form_id).strip("_") or "form"
    filename = f"filled_{safe_id}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    out_path = os.path.join(_ARTIFACTS_DIR, filename)
    pdf.output(out_path)
    return out_path


@server.call_tool()
async def handle_call_tool(name: str, arguments: dict | None) -> list[TextContent]:
    arguments = arguments or {}

    if name == "parse_form_fields":
        form_id = arguments.get("form_id", "")
        fields = kb.lookup_form(form_id)
        if not fields:
            known = ", ".join(kb.known_form_names())
            return [TextContent(
                type="text",
                text=(f"NOT_FOUND: I don't have a stored template for '{form_id}'. "
                      f"Known forms: {known}. Best option: ask the user to upload the form so "
                      f"'form_reader' can read it directly. If they only have the name, call "
                      f"'research_form_fields' to look its required fields up from official sources."),
            )]
        lines = "\n".join(f"{i}. {label} - {desc}" for i, (label, desc) in enumerate(fields, 1))
        return [TextContent(type="text", text=f"Required fields for {form_id.upper()}:\n{lines}")]

    if name == "lookup_govt_scheme":
        scheme_name = arguments.get("scheme_name", "")
        scheme = kb.lookup_scheme(scheme_name)
        if not scheme:
            known = ", ".join(kb.known_scheme_names())
            return [TextContent(
                type="text",
                text=(f"NOT_FOUND: I don't have curated details for '{scheme_name}'. "
                      f"Known schemes: {known}. Call 'research_govt_scheme' to fetch it from "
                      f"official web sources — it will remember the result for next time."),
            )]
        lines = [
            scheme["full_name"],
            f"- Benefit: {scheme['benefit']}",
            f"- Eligibility: {scheme['eligibility']}",
            f"- Documents needed: {scheme['documents']}",
        ]
        if scheme.get("origin") == "grounded" and scheme.get("sources"):
            lines.append("- Sources: " + ", ".join(scheme["sources"]))
        return [TextContent(type="text", text="\n".join(lines))]

    if name == "generate_filled_pdf":
        form_id = arguments.get("form_id", "form")
        raw = arguments.get("user_data", "{}")
        try:
            data = json.loads(raw) if isinstance(raw, str) else dict(raw)
            if not isinstance(data, dict):
                raise ValueError("user_data must be a JSON object of field -> value")
        except (json.JSONDecodeError, ValueError) as exc:
            return [TextContent(type="text", text=f"ERROR: could not parse user_data ({exc}). Expected a JSON object.")]
        if not data:
            return [TextContent(type="text", text="ERROR: no user data was provided, so there is nothing to fill.")]
        try:
            path = _build_pdf(form_id, data)
        except Exception as exc:  # pragma: no cover - surfaced to the agent
            return [TextContent(type="text", text=f"ERROR generating PDF: {exc}")]
        return [TextContent(
            type="text",
            text=f"SUCCESS: filled {form_id.upper()} PDF generated with {len(data)} field(s) and saved at:\n{path}",
        )]

    raise ValueError(f"Unknown tool: {name}")


async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="sugam-mcp",
                server_version="1.0.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
